---
kind: Service
apiversion: v1
metadata:
  name: helloworldservices
spec:
   selector:
        app: hello-world
   ports:
      port: 8080  #port accessible inside the cluster
      targetPort: 80 #port to forward to inside the pod
      nodePort: 30001  #port accessible outside cluster
   type: LoadBalancer



      
